Window.SetBackgroundTopColor (0.0, 0.0, 0.0);
Window.SetBackgroundBottomColor (0.0, 0.0, 0.0);

logo_image = Image("infiltrator-os.png");
logo_sprite = Sprite(logo_image);

fun position_logo ()
{
    screen_width = Window.GetWidth();
    screen_height = Window.GetHeight();
    image_width = logo_image.GetWidth();
    image_height = logo_image.GetHeight();

    logo_sprite.SetX((screen_width - image_width) / 2);
    logo_sprite.SetY((screen_height - image_height) / 2);
    logo_sprite.SetZ(100);
}

Plymouth.SetRefreshFunction(position_logo);
position_logo();
